name: Zstats
version: 0.8
main: zerrium.Zstats
api-version: 1.12
author: zerrium
softdepend: [DiscordSRV, Essentials]
commands:
  zstats:
    description: Modify player stats data on database
    usage: /zstats <update/delete> <player_name>
    permission: Zstats.use